/**
 * Prisma client with lazy initialization to avoid Vercel build failures
 * when DATABASE_URL is not available at build time.
 *
 * NOTE: The PrismaClient type is generated by `prisma generate`.
 * If you see type errors, run: pnpm db:generate
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let PrismaClientClass: any = null;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let prismaInstance: any = null;

/**
 * Load PrismaClient dynamically to avoid build-time errors
 * when the generated client doesn't exist yet.
 */
async function loadPrismaClient() {
  if (!PrismaClientClass) {
    try {
      // Dynamic import - handle both default and named exports
      const module = await import('@prisma/client');
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      PrismaClientClass = (module as any).PrismaClient || (module as any).default?.PrismaClient;
      if (!PrismaClientClass) {
        throw new Error('PrismaClient not found in module');
      }
    } catch {
      throw new Error(
        'Prisma Client not generated. Run: pnpm db:generate'
      );
    }
  }
  return PrismaClientClass;
}

/**
 * Get the Prisma client instance. Lazily initialized to prevent
 * build-time errors when DATABASE_URL is not set.
 *
 * @throws Error if DATABASE_URL is not set or Prisma client isn't generated
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function getPrismaClientAsync(): Promise<any> {
  if (!prismaInstance) {
    if (!process.env.DATABASE_URL) {
      throw new Error(
        'DATABASE_URL environment variable is not set. ' +
        'Please configure your Neon database connection string.'
      );
    }
    const Client = await loadPrismaClient();
    prismaInstance = new Client({
      log: process.env.NODE_ENV === 'development' ? ['warn', 'error'] : ['error'],
    });
  }
  return prismaInstance;
}

/**
 * Synchronous version for cases where async isn't feasible.
 * Requires that PrismaClient has been loaded first.
 *
 * @throws Error if Prisma client hasn't been initialized
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getPrismaClient(): any {
  if (!prismaInstance) {
    // Try synchronous import (will work after first async init or if already loaded)
    try {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const { PrismaClient } = require('@prisma/client');
      if (!process.env.DATABASE_URL) {
        throw new Error(
          'DATABASE_URL environment variable is not set. ' +
          'Please configure your Neon database connection string.'
        );
      }
      prismaInstance = new PrismaClient({
        log: process.env.NODE_ENV === 'development' ? ['warn', 'error'] : ['error'],
      });
    } catch {
      throw new Error(
        'Prisma Client not available. Ensure DATABASE_URL is set and run: pnpm db:generate'
      );
    }
  }
  return prismaInstance;
}

/**
 * Disconnect the Prisma client (for graceful shutdown)
 */
export async function disconnectPrisma(): Promise<void> {
  if (prismaInstance) {
    await prismaInstance.$disconnect();
    prismaInstance = null;
  }
}
